# Generated by Django 2.2.3 on 2019-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=56)),
                ('email', models.CharField(max_length=56)),
                ('password', models.CharField(max_length=76)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
