# Generated by Django 2.2.3 on 2019-08-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginwithauth', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('queAndAnsr', models.TextField()),
                ('geo_tag', models.TextField()),
                ('device_signature', models.TextField()),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
